apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-label
  template:
    metadata:
      labels:
        app: back-label
    spec:
      containers:
      - name: back-container
        image: abhishek661/back-image:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: MYSQL_DATABASE

