apiVersion: apps/v1
Kind: Deployment
metadata:
  name: back-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-label
  templates:
    metadata:
      labels:
        app: back-label
    spec:
      containers:
      - name: back-container
        image: abhishek661/back-image:latest
        ports:
        -  containerPort: 5000
        env:
        - name: MYSQL_HOST
        - name: mysql-service
