apiVersion: v1
kind: Ingress
metadata:
  name: back-ingress
spec:
  rules:
  - host: back.app
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: back-service
            port:
              number: 5000

      
    
